
export const universities = [
  { value: "Abia State University", label: "Abia State University" },
  { value: "Abubakar Tafawa Balewa University", label: "Abubakar Tafawa Balewa University" },
  { value: "Achievers University", label: "Achievers University" },
  { value: "Adamawa State University", label: "Adamawa State University" },
  { value: "Adekunle Ajasin University", label: "Adekunle Ajasin University" },
  { value: "Adeleke University", label: "Adeleke University" },
  { value: "Admiralty University of Nigeria", label: "Admiralty University of Nigeria" },
  { value: "Afe Babalola University", label: "Afe Babalola University" },
  { value: "African University of Science and Technology", label: "African University of Science and Technology" },
  { value: "Ahmadu Bello University", label: "Ahmadu Bello University" },
  { value: "Ajayi Crowther University", label: "Ajayi Crowther University" },
  { value: "Akwa Ibom State University", label: "Akwa Ibom State University" },
  { value: "Alex Ekwueme Federal University, Ndufu-Alike", label: "Alex Ekwueme Federal University, Ndufu-Alike" },
  { value: "Al-Hikmah University", label: "Al-Hikmah University" },
  { value: "Al-Qalam University, Katsina", label: "Al-Qalam University, Katsina" },
  { value: "Ambrose Alli University", label: "Ambrose Alli University" },
  { value:"American University of Nigeria", label: "American University of Nigeria" },
  { value: "Anambra State University", label: "Anambra State University" },
  { value: "Augustine University", label: "Augustine University" },
  { value: "Babcock University", label: "Babcock University" },
  { value: "Bauchi State University", label: "Bauchi State University" },
  { value: "Bayero University Kano", label: "Bayero University Kano" },
  { value: "Baze University", label: "Baze University" },
  { value: "Bells University of Technology", label: "Bells University of Technology" },
  { value: "Benson Idahosa University", label: "Benson Idahosa University" },
  { value: "Benue State University", label: "Benue State University" },
  { value: "Bingham University", label: "Bingham University" },
  { value: "Bowen University", label: "Bowen University" },
  { value: "Caleb University", label: "Caleb University" },
  { value: "Caritas University", label: "Caritas University" },
  { value: "Chrisland University", label: "Chrisland University" },
  { value: "Christopher University", label: "Christopher University" },
  { value: "Chukwuemeka Odumegwu Ojukwu University", label: "Chukwuemeka Odumegwu Ojukwu University" },
  { value: "Clifford University", label: "Clifford University" },
  { value: "Coal City University", label: "Coal City University" },
  { value: "Covenant University", label: "Covenant University" },
  { value: "Crawford University", label: "Crawford University" },
  { value: "Crescent University", label: "Crescent University" },
  { value: "Cross River University of Technology", label: "Cross River University of Technology" },
_   { value: "Crown Hill University", label: "Crown Hill University" },
_   { value: "Delta State University, Abraka", label: "Delta State University, Abraka" },
_   { value: "Dominican University, Ibadan", label: "Dominican University, Ibadan" },
_   { value: "Eastern Palm University", label: "Eastern Palm University" },
_   { value: "Ebonyi State University", label: "Ebonyi State University" },
_   { value "Edo University, Iyamho", label: "Edo University, Iyamho" },
_   { value: "Edwin Clark University", label: "Edwin Clark University" },
_   { value: "Ekiti State University, Ado Ekiti", label: "Ekiti State University, Ado Ekiti" },
_   { value: "Elizade University", label: "Elizade University" },
_   { value: "Enugu State University of Science and Technology", label: "Enugu State University of Science and Technology" },
_   { value: "Evangel University, Akaeze", label: "Evangel University, Akaeze" },
_   { value: "Federal University of Agriculture, Abeokuta", label: "Federal University of Agriculture, Abeokuta" },
_   { value: "Federal University of Petroleum Resources, Effurun", label: "Federal University of Petroleum Resources, Effurun" },
_   { value: "Federal University of Technology, Akure", label: "Federal University of Technology, Akure" },
_   { value: "Federal University of Technology, Minna", label: "Federal University of Technology, Minna" },
_   { value: "Federal University of Technology, Owerri", label: "Federal University of Technology, Owerri" },
_   { value: "Federal University, Birnin Kebbi", label: "Federal University, Birnin Kebbi" },
_   { value: "Federal University, Dutse, Jigawa State", label: "Federal University, Dutse, Jigawa State" },
_   { value: "Federal University, Dutsin-Ma, Katsina", label: "Federal University, Dutsin-Ma, Katsina" },
_   { value: "Federal University, Gashua, Yobe", label: "Federal University, Gashua, Yobe" },
_   { value: "Federal University, Gusau", label: "Federal University, Gusau" },
_   { value: "Federal University, Kashere, Gombe State", label: "Federal University, Kashere, Gombe State" },
_   { value: "Federal University, Lafia, Nasarawa State", label: "Federal University, Lafia, Nasarawa State" },
_   { value: "Federal University, Lokoja, Kogi State", label: "Federal University, Lokoja, Kogi State" },
_   { value: "Federal University, Otuoke, Bayelsa", label: "Federal University, Otuoke, Bayelsa" },
_   { value: "Federal University, Oye-Ekiti, Ekiti State", label: "Federal University, Oye-Ekiti, Ekiti State" },
_   { value_:"Federal University, Wukari, Taraba State", label: "Federal University, Wukari, Taraba State" },
_   { value: "Fountain University, Osogbo", label: "Fountain University, Osogbo" },
_   { value: "Glorious Vision University", label: "Glorious Vision University" },
_   { value: "Godfrey Okoye University", label: "Godfrey Okoye University" },
_   { value: "Gombe State University", label: "Gombe State University" },
_   { value: "Gregory University, Uturu", label: "Gregory University, Uturu" },
_   { value: "Hallmark University, Ijebu-Itele", label: "Hallmark University, Ijebu-Itele" },
_   { value: "Hezekiah University", label: "Hezekiah University" },
_   { value: "Ibrahim Badamasi Babangida University, Lapai", label: "Ibrahim Badamasi Babangida University, Lapai" },
_   { value: "Igbinedion University Okada", label: "Igbinedion University Okada" },
_   { value: "Ignatius Ajuru University of Education", label: "Ignatius Ajuru University of Education" },
_   { value: "Imo State University", label: "Imo State University" },
_   { value: "Joseph Ayo Babalola University", label: "Joseph Ayo Babalola University" },
_   { value: "Kaduna State University", label: "Kaduna State University" },
_   { value: "Kano University of Science and Technology, Wudil", label: "Kano University of Science and Technology, Wudil" },
_   { value: "Kebbi State University of Science and Technology", label: "Kebbi State University of Science and Technology" },
_   { value: "Kings University", label: "Kings University" },
_   { value: "Kogi State University", label: "Kogi State University" },
_   { value: "Kola Daisi University", label: "Kola Daisi University" },
_   { value: "Kwara State University", label: "Kwara State University" },
_   { value: "Kwararafa University, Wukari", label: "Kwararafa University, Wukari" },
_   { value: "Ladoke Akintola University of Technology", label: "Ladoke Akintola University of Technology" },
_   { value: "Lagos State University", label: "Lagos State University" },
_   { value: "Landmark University", label: "Landmark University" },
_   { value: "Lead City University", label: "Lead City University" },
_   { value: "Legacy University, Okija", label: "Legacy University, Okija" },
_   { value: "Madonna University, Okija", label: "Madonna University, Okija" },
_   { value:"Mcpherson University", label: "Mcpherson University" },
_   { value: "Michael and Cecilia Ibru University", label: "Michael and Cecilia Ibru University" },
_   { value: "Michael Okpara University of Agriculture, Umudike", label: "Michael Okpara University of Agriculture, Umudike" },
_   { value: "Modibbo Adama University of Technology, Yola", label: "Modibbo Adama University of Technology, Yola" },
_   { value: "Moshood Abiola University of Science and Technology, Abeokuta", label: "Moshood Abiola University of Science and Technology, Abeokuta" },
_   { value: "Mountain Top University", label: "Mountain Top University" },
_   { value: "Nasarawa State University", label: "Nasarawa State University" },
_   { value: "Niger Delta University", label: "Niger Delta University" },
_   { value: "Nigeria Police Academy, Wudil", label: "Nigeria Police Academy, Wudil" },
_   { value: "Nigerian Army University, Biu", label: "Nigerian Army University, Biu" },
_   { value: "Nigerian Defence Academy", label: "Nigerian Defence Academy" },
_   { value: "Nigerian Maritime University, Okerenkoko", label: "Nigerian Maritime University, Okerenkoko" },
_   { value: "Nile University of Nigeria", label: "Nile University of Nigeria" },
_   { value: "Nnamdi Azikiwe University, Awka", label: "Nnamdi Azikiwe University, Awka" },
_   { value: "Northwest University, Kano", label: "Northwest University, Kano" },
_   { value: "Novena University", label: "Novena University" },
_   { value: "Obafemi Awolowo University", label: "Obafemi Awolowo University" },
_   { value: "Obong University", label: "Obong University" },
_   { value: "Oduduwa University", label: "Oduduwa University" },
_   { value: "Olabisi Onabanjo University", label: "Olabisi Onabanjo University" },
_   { value: "Ondo State University of Science and Technology", label: "Ondo State University of Science and Technology" },
_   { value: "PAMO University of Medical Sciences", label: "PAMO University of Medical Sciences" },
_   { value: "Pan-Atlantic University", label: "Pan-Atlantic University" },
_   { value: "Paul University", label: "Paul University" },
_   { value: "Plateau State University", label: "Plateau State University" },
_   { value: "Precious Cornerstone University", label: "Precious Cornerstone University" },
_   { value: "Redeemer's University", label: "Redeemer's University" },
_   { value: "Renaissance University", label: "Renaissance University" },
_   { value: "Rhema University", label: "Rhema University" },
_   { value: "Ritman University", label: "Ritman University" },
_   { value: "Rivers State University", label: "Rivers State University" },
_   { value: "Salem University", label: "Salem University" },
_   { value: "Samuel Adegboyega University", label: "Samuel Adegboyega University" },
_   { value: "Sokoto State University", label: "Sokoto State University" },
_   { value: "Southwestern University, Nigeria", label: "Southwestern University, Nigeria" },
_   { value: "Spiritan University, Nneochi", label: "Spiritan University, Nneochi" },
_   { value: "Sule Lamido University", label: "Sule Lamido University" },
_   { value: "Summit University Offa", label: "Summit University Offa" },
_   { value: "Tai Solarin University of Education", label: "Tai Solarin University of Education" },
_   { value: "Tansian University", label: "Tansian University" },
_   { value: "Taraba State University", label: "Taraba State University" },
_   { value: "The Technical University, Ibadan", label: "The Technical University, Ibadan" },
_   { value: "Umaru Musa Yar'Adua University", label: "Umaru Musa Yar'Adua University" },
_   { value: "University of Abuja", label: "University of Abuja" },
_   { value: "University of Africa, Toru-Orua", label: "University of Africa, Toru-Orua" },
_   { value: "University of Agriculture, Makurdi", label: "University of Agriculture, Makurdi" },
_   { value: "University of Benin", label: "University of Benin" },
_   { value: "University of Calabar", label: "University of Calabar" },
_   { value: "University of Ibadan", label: "University of Ibadan" },
_   { value: "University of Ilorin", label: "University of Ilorin" },
_   { value: "University of Jos", label: "University of Jos" },
_   { value: "University of Lagos", label: "University of Lagos" },
_   { value: "University of Maiduguri", label: "University of Maiduguri" },
_   { value: "University of Medical Sciences, Ondo", label: "University of Medical Sciences, Ondo" },
_   { value: "University of Mkar", label: "University of Mkar" },
_   { value: "University of Nigeria, Nsukka", label: "University of Nigeria, Nsukka" },
_   { value: "University of Port Harcourt", label: "University of Port Harcourt" },
_   { value: "University of Uyo", label: "University of Uyo" },
_   { value: "Usmanu Danfodiyo University", label: "Usmanu Danfodiyo University" },
_   { value: "Veritas University", label: "Veritas University" },
_   { value: "Wellspring University", label: "Wellspring University" },
_   { value: "Wesley University of Science and Technology", label: "Wesley University of Science and Technology" },
_   { value: "Western Delta University", label: "Western Delta University" },
_   { value: "Yobe State University", label: "Yobe State University" },
];
